
export const API = 'http://localhost:1375/';

export const ADD_PERSON = 'ADD_PERSON';
export const ADD_PERSON_LOADER= 'ADD_PERSON_LOADER';
export const ADD_PERSON_ERR='ADD_PERSON_ERR';

export const GET_PERSONS='GET_PERSONS';
export const GET_PERSONS_LOADER='GET_PERSONS_LOADER';
export const GET_PERSONS_ERR='GET_PERSONS_ERR';

export const SET_CURRENT_PROFESOR='SET_CURRENT_PROFESOR';

export const GET_AUTH_REGISTER = 'GET_AUTH_REGISTER';
export const GET_AUTH_REGISTER_LOAD = 'GET_AUTH_REGISTER_LOAD';
export const GET_AUTH_REGISTER_ERR = 'GET_AUTH_REGISTER_ERR';

export const GET_AUTH_TOKEN = 'GET_AUTH_TOKEN';
export const GET_AUTH_TOKEN_LOAD = 'GET_AUTH_TOKEN_LOAD';
export const GET_AUTH_TOKEN_ERR = 'GET_AUTH_TOKEN_ERR';
export const UNAUTH_USER = 'UNAUTH_USER';

